# Generated by Django 4.2 on 2023-05-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PUID',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
