# Generated by Django 4.2 on 2023-10-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='llm_form',
            new_name='llm_data',
        ),
    ]
