# Generated by Django 4.2 on 2023-10-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_rename_llm_form_llm_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llm_data',
            old_name='system_response',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='llm_data',
            old_name='user_prompt',
            new_name='response',
        ),
    ]
