# Generated by Django 4.2 on 2023-10-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_rename_system_response_llm_data_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm_data',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
