# Generated by Django 4.2 on 2023-05-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.CharField(max_length=25)),
                ('click_location', models.CharField(max_length=25)),
                ('time_stamp', models.CharField(max_length=100)),
            ],
        ),
    ]
