# Generated by Django 4.2 on 2023-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicks',
            name='click_count',
        ),
        migrations.AddField(
            model_name='clicks',
            name='user',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
