# Generated by Django 4.2 on 2023-05-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0002_remove_clicks_click_count_clicks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='event',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='click_location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='time_stamp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
