# Generated by Django 4.2 on 2023-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0003_clicks_event_alter_clicks_click_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clicks',
            old_name='click_location',
            new_name='mouseX',
        ),
        migrations.AddField(
            model_name='clicks',
            name='mouseY',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
